"""Abstract base class for child-agent adaptation layers."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any


@dataclass
class AdapterConfig:
    """Configuration bundle passed to an adapter at construction time.

    Attributes:
        adapter_id: Unique identifier for this adapter instance.
        params: Arbitrary key-value parameters (domain, task, thresholds, …).
    """

    adapter_id: str
    params: dict[str, Any] = field(default_factory=dict)


class BaseAdapter(ABC):
    """Transforms a prompt *before* it reaches the backbone (pre-processing)
    and optionally post-processes the backbone's output.

    The lightweight customisation performed by adapters is the primary
    mechanism through which a :class:`~mother_agent.ChildAgent` differs from
    its parent :class:`~mother_agent.MotherAgent` without requiring a separate
    copy of model weights.
    """

    def __init__(self, config: AdapterConfig) -> None:
        self.config = config

    @abstractmethod
    def adapt_prompt(self, prompt: str, context: dict[str, Any] | None = None) -> str:
        """Return a modified *prompt* tailored for this adapter's task.

        Args:
            prompt: Original user/agent input.
            context: Optional context dictionary.

        Returns:
            Adapted prompt string.
        """

    def adapt_output(self, output: str, context: dict[str, Any] | None = None) -> str:
        """Optionally post-process the backbone's generated *output*.

        The default implementation returns *output* unchanged.

        Args:
            output: Text generated by the backbone.
            context: Optional context dictionary.

        Returns:
            Possibly modified output string.
        """
        return output

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(id={self.config.adapter_id!r})"
